### ISSUE TITLE
dart 2 problem!

### ISSUE THREAD

**Issue by nimasedgahatnia** [deven98/flutter_chess_board#17]
```
Because chess depends on flutter_chess_board ^0.9.4 which depends on chess >=0.6.5 <1.0.0, chess >=0.6.5 <1.0.0 is required.
So, because chess is 1.0.0+1, version solving failed.
pub get failed (1; So, because chess is 1.0.0+1, version solving failed.)

```

**Comment by deven98** [comment]
Hey @nimasedgahatnia, this should be solved now. Closing this, please reopen if any issue comes up. Thanks!

**Comment by Mihirsinh-01** [comment]
Still Getting the same error.

**Comment by TafadzwaD** [comment]
@Mihirsinh-01 a dependency override of the
<img width="852" alt="chess_override" src="https://user-images.githubusercontent.com/28431370/141432611-3d5b8d48-388b-47cc-8840-537e6db8eaba.png">
 chess package solved my issue
