### ISSUE TITLE
[Feature Request] Adding arrows to plan moves

### ISSUE THREAD

**Issue by datteroandrea** [deven98/flutter_chess_board#20]
Would be a lot appreciated the adding of a feature that allows players to draw arrows in the board

**Comment by deven98** [comment]
Hi @datteroandrea,

The latest release now contains the ability to add arrows onto the board:

https://pub.dev/packages/flutter_chess_board

Hope this helps :)

**Comment by datteroandrea** [comment]
That's great, awesome!
