### ISSUE TITLE
Check Event

### ISSUE THREAD

**Issue by vichuer** [deven98/flutter_chess_board#22]
I need help with check event.
How to know if the player got check or not?
I didn't see anything regarding that. In older version there was a onCheck event.

**Comment by d3xvn** [comment]
Hey @vichuer, somehow the `isInCheck` function slipped past me in the refactor. 

I just updated the package (v1.0.1) to support this: https://pub.dev/packages/flutter_chess_board

A `ChessBoardController` is now required (in v1.x.x) to be attached when a `ChessBoard` is shown. 
To check whether the position is in check, you can use `controller.isInCheck()`. 

If you need to listen to board events, you can add a listener to the controller as well as shown in the README.md. 

Hope this helps. Feel free to reopen this if you have any other doubts. 

Best,
Deven

**Comment by vichuer** [comment]
Thanks a lot for replying. I will update the package immediately.
