### ISSUE TITLE
include method controller.move(move)

### ISSUE THREAD

**Issue by chessasuke** [deven98/flutter_chess_board#9]
Hi, can you add the method controller.move() e.x controller.move('Nf3') ? Currently, there is only makeMove which takes two strings (from: , to: ) ,but this is not very used in chess notations. To create a viewer to reproduce games from pgn files it will be easier, plus it's just two lines of code :)

**Comment by deven98** [comment]
Added support for multiple kinds of moves in the new controller architecture: 

https://pub.dev/packages/flutter_chess_board

Thanks.
